name: Build APK

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Configurar chaves
        run: |
          sed -i "s/String apiKey = '';/String apiKey = 'AQ.Ab8RN6KlCBReFr9m_ryowVQpqTmwHh6UoRRfkaGAjgLEbGz5mA';/" lib/helper/global.dart
          sed -i "s/String gptKey = '';/String gptKey = '';/" lib/helper/global.dart
          sed -i "s/String claudeKey = '';/String claudeKey = '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';/" lib/helper/global.dart
          sed -i "s/String xiaoAiKey = '';/String xiaoAiKey = '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';/" lib/helper/global.dart

      - name: Get packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ai-assistant-apk
          path: build/app/outputs/flutter-apk/app-release.apk
